/* eslint-disable @next/next/no-img-element */
import * as React from 'react';

export interface EmailTemplateProps {
  firstName: string;
  lastName?: string;
  email: string;
  phone?: string;
  message: string;
  logoUrl?: string;
}

export function EmailTemplate({ firstName, lastName, email, phone, message, logoUrl }: EmailTemplateProps) {
  const fullName = [firstName, lastName].filter(Boolean).join(' ');
  return (
    <div style={{ backgroundColor: '#0f0e0d', color: '#ffffff', fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', Arial, 'Noto Sans', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'", padding: '24px' }}>
      <table role="presentation" width="100%" cellPadding={0} cellSpacing={0} style={{ maxWidth: 640, margin: '0 auto', backgroundColor: '#151311', borderRadius: 16, overflow: 'hidden', border: '1px solid #2a2623' }}>
        <tbody>
          <tr>
            <td style={{ padding: 24, background: 'linear-gradient(90deg, rgba(251,103,3,0.08), rgba(251,103,3,0.02))' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                {logoUrl ? (
                  <img src={logoUrl} width={140} height={48} alt="Precision Details" style={{ display: 'block' }} />
                ) : (
                  <div style={{ fontSize: 18, fontWeight: 800, letterSpacing: 0.5 }}>Precision Details</div>
                )}
              </div>
            </td>
          </tr>
          <tr>
            <td style={{ padding: '8px 24px' }}>
              <div style={{ height: 1, width: '100%', backgroundColor: '#2a2623' }} />
            </td>
          </tr>
          <tr>
            <td style={{ padding: 24 }}>
              <h1 style={{ margin: 0, fontSize: 22, lineHeight: '28px', fontWeight: 800 }}>New contact request</h1>
              <p style={{ margin: '8px 0 0 0', color: '#c0bbb7', fontSize: 14 }}>You received a new message from the website contact form.</p>

              <table role="presentation" width="100%" cellPadding={0} cellSpacing={0} style={{ marginTop: 16, borderCollapse: 'separate', borderSpacing: 0 }}>
                <tbody>
                  <tr>
                    <td style={cellLabelStyle}>Name</td>
                    <td style={cellValueStyle}>{fullName || '—'}</td>
                  </tr>
                  <tr>
                    <td style={cellLabelStyle}>Email</td>
                    <td style={cellValueStyle}><a href={`mailto:${email}`} style={linkStyle}>{email}</a></td>
                  </tr>
                  <tr>
                    <td style={cellLabelStyle}>Phone</td>
                    <td style={cellValueStyle}>{phone || '—'}</td>
                  </tr>
                  <tr>
                    <td style={{ ...cellLabelStyle, verticalAlign: 'top' }}>Message</td>
                    <td style={{ ...cellValueStyle, whiteSpace: 'pre-wrap' }}>{message}</td>
                  </tr>
                </tbody>
              </table>

              <div style={{ marginTop: 16, padding: 12, backgroundColor: '#201d1a', border: '1px solid #2a2623', borderRadius: 12, color: '#c0bbb7', fontSize: 12 }}>
                This email was generated by the Precision Details website. Reply directly to contact the sender.
              </div>
            </td>
          </tr>
          <tr>
            <td style={{ padding: 16, textAlign: 'center', backgroundColor: '#100e0d', borderTop: '1px solid #2a2623', color: '#8e8781', fontSize: 12 }}>
              © {new Date().getFullYear()} Precision Details
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

const cellLabelStyle: React.CSSProperties = {
  width: 120,
  padding: '10px 12px',
  fontSize: 12,
  color: '#8e8781',
  backgroundColor: '#1b1916',
  border: '1px solid #2a2623',
  borderRight: 'none',
  borderTopLeftRadius: 8,
  borderBottomLeftRadius: 8,
};

const cellValueStyle: React.CSSProperties = {
  padding: '10px 12px',
  fontSize: 14,
  color: '#ffffff',
  backgroundColor: '#151311',
  border: '1px solid #2a2623',
  borderLeft: 'none',
  borderTopRightRadius: 8,
  borderBottomRightRadius: 8,
};

const linkStyle: React.CSSProperties = {
  color: '#fb6703',
  textDecoration: 'none',
};